server:
  port: 9090
spring:
  sql:
    init:
      mode: "always"
  datasource:
    url: "jdbc:h2:file:./db/svc_db.mv.db"
    driverClassName: "org.h2.Driver"
    username: "svc"
    password: "qwe123"
  h2:
    console:
      enabled: true